# Generated by Django 2.2 on 2019-05-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190529_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='phone',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
