# Generated by Django 2.2 on 2019-05-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20190529_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administration',
            options={'ordering': ['-id']},
        ),
    ]
