# Generated by Django 2.2 on 2019-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_administration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
